name: Setup repository
on:
    create:
    workflow_dispatch:
jobs:
    setup-repository:
        #  prettier-ignore
        if: ${{ github.event.ref }} == 'refs/heads/${{ github.event.repository.default_branch }}' 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1
            - name: Create variables
              continue-on-error: true
              env:
                  GH_TOKEN: ${{ secrets.CICD_TOKEN }}
              run: sh scripts/set_variables.sh
            - name: Create secrets
              continue-on-error: true
              env:
                  GH_TOKEN: ${{ secrets.CICD_TOKEN }}
              run: sh scripts/set_secrets.sh
